### ISSUE TITLE
index.js does not provide an export named 'default'错误

### ISSUE THREAD

**Issue by liujiujin2006** [cangshudada/vue-keyBoard-next#1]
使用vite的vue项目中引入会出现
Uncaught SyntaxError: The requested module '/node_modules/vue-keyboard-virtual-next/index.js?v=b11119b8' does not provide an export named 'default'

**Comment by cangshudada** [comment]
抱歉，最好能在codeSandBox中提供相应错误用例，目前经测试在vite最新版本中无论是全局引入还是局部引入都是没有复现这个问题的
以下是codeSandBox中测试情况
https://codesandbox.io/s/vite-vue3-keyboard-18oo4

**Comment by liujiujin2006** [comment]
> 抱歉，最好能在codeSandBox中提供相应错误用例，目前经测试在vite最新版本中无论是全局引入还是局部引入都是没有复现这个问题的
> 以下是codeSandBox中测试情况
> https://codesandbox.io/s/vite-vue3-keyboard-18oo4

抱歉，最后在原来项目中排查，我查到问题所在。我同时使用了vue-echarts，并且在vite配置optimizeDeps 里排除vue-echarts。然后就出了问题，事实上，使用vue-keyBoard-next不能排除vue-echarts，否则就会出问题。
codeSandBox中对vite的配置貌似不会生效，需要导出再运行
https://codesandbox.io/s/practical-burnell-7m6yj

**Comment by cangshudada** [comment]
> > 抱歉，最好能在codeSandBox中提供相应错误用例，目前经测试在vite最新版本中无论是全局引入还是局部引入都是没有复现这个问题的
> > 以下是codeSandBox中测试情况
> > https://codesandbox.io/s/vite-vue3-keyboard-18oo4
> 
> 抱歉，最后在原来项目中排查，我查到问题所在。我同时使用了vue-echarts，并且在vite配置optimizeDeps 里排除vue-echarts。然后就出了问题，事实上，使用vue-keyBoard-next不能排除vue-echarts，否则就会出问题。
> codeSandBox中对vite的配置貌似不会生效，需要导出再运行
> https://codesandbox.io/s/practical-burnell-7m6yj

目前vue-keyBoard-next是umd的打包模式，vite会直接通过esm的模式引入组件，在vite.config.js中强制排除预构建通过esm的方式引入肯定是会报错的。目前大部分主流库都是umd的打包方式，不建议在exclude中排除的这些库的预构建引入。
解决方法如下
`
  optimizeDeps: {
    include: ["vue-keyboard-virtual-next", "vue-echarts", "echarts"],
    exclude: []
  },
 // or
 optimizeDeps: {
    include: [],
    exclude: []
  },
`

**Comment by liujiujin2006** [comment]
> > > 抱歉，最好能在codeSandBox中提供相应错误用例，目前经测试在vite最新版本中无论是全局引入还是局部引入都是没有复现这个问题的
> > > 以下是codeSandBox中测试情况
> > > https://codesandbox.io/s/vite-vue3-keyboard-18oo4
> > 
> > 
> > 抱歉，最后在原来项目中排查，我查到问题所在。我同时使用了vue-echarts，并且在vite配置optimizeDeps 里排除vue-echarts。然后就出了问题，事实上，使用vue-keyBoard-next不能排除vue-echarts，否则就会出问题。
> > codeSandBox中对vite的配置貌似不会生效，需要导出再运行
> > https://codesandbox.io/s/practical-burnell-7m6yj
> 
> 目前vue-keyBoard-next是umd的打包模式，vite会直接通过esm的模式引入组件，在vite.config.js中强制排除预构建通过esm的方式引入肯定是会报错的。目前大部分主流库都是umd的打包方式，不建议在exclude中排除的这些库的预构建引入。
> 解决方法如下
> `optimizeDeps: { include: ["vue-keyboard-virtual-next", "vue-echarts", "echarts"], exclude: [] }, // or optimizeDeps: { include: [], exclude: [] },`

感谢，已经搞定
