### ISSUE TITLE
请问怎么才能改变键盘弹出的位置

### ISSUE THREAD

**Issue by TangStudio** [cangshudada/vue-keyBoard-next#11]
如题，在浏览器窗口最大化后，键盘弹出的位置都会挡住输入框，有办法调整每次键盘弹出的默认位置吗，感谢

**Comment by cangshudada** [comment]
> 如题，在浏览器窗口最大化后，键盘弹出的位置都会挡住输入框，有办法调整每次键盘弹出的默认位置吗，感谢

支持传入自定义动画类名：animateClass，自己写相关展示动画css即可

**Comment by cangshudada** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/40785860/236435152-8f5ad37a-8c9e-4df6-a979-c69214db525f.png">
