### ISSUE TITLE
不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange等事件

### ISSUE THREAD

**Issue by liujiujin2006** [cangshudada/vue-keyBoard-next#2]
不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue

**Comment by cangshudada** [comment]
> 不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
> https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue

不指定v-model时，键盘会自动与聚焦的输入框建立注册关系，此时键盘只会与最初的输入框value值做一次绑定，而不会是双向绑定。目前在你的用例中暂未发现输入框中value未改变以及不触发change事件的情况在，这是我这边的录屏结果。

![vite-keyboard](https://user-images.githubusercontent.com/40785860/115982706-ae899e80-a5cf-11eb-9196-ae85228f3d88.gif)

![vite-keyboard-change](https://user-images.githubusercontent.com/40785860/115982708-b5b0ac80-a5cf-11eb-9db9-38a2074f9191.gif)

**Comment by cangshudada** [comment]
> 不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
> https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue

可以再fork看下抛出的钩子调用情况 https://codesandbox.io/s/vite-vue3-keyboard-18oo4?file=/src/App.vue

**Comment by liujiujin2006** [comment]
> > 不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
> > https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue
> 
> 可以再fork看下抛出的钩子调用情况 https://codesandbox.io/s/vite-vue3-keyboard-18oo4?file=/src/App.vue

大概明白了，这种模式使用虚拟键盘输入时只是通过js改变了当前聚焦input的值，并不会触发input原生onchange事件，假如有个表单如下:

```
  <div class="form-group">
    <label>账号</label>
    <input data-mode="number" class="form-control" v-model="name" />
  </div>
  <div class="form-group">
    <label>密码</label>
    <input data-mode="en" type="password" class="form-control" v-model="psw" />
  </div>
```

如何才能比较方便的做双向数据绑定呢？

**Comment by cangshudada** [comment]
> > > 不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
> > > https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue
> > 
> > 
> > 可以再fork看下抛出的钩子调用情况 https://codesandbox.io/s/vite-vue3-keyboard-18oo4?file=/src/App.vue
> 
> 大概明白了，这种模式使用虚拟键盘输入时只是通过js改变了当前聚焦input的值，并不会触发input原生onchange事件，假如有个表单如下:
> 
> ```
>   <div class="form-group">
>     <label>账号</label>
>     <input data-mode="number" class="form-control" v-model="name" />
>   </div>
>   <div class="form-group">
>     <label>密码</label>
>     <input data-mode="en" type="password" class="form-control" v-model="psw" />
>   </div>
> ```
> 
> 如何才能比较方便的做双向数据绑定呢？

v1.0.1版本新增了form表单的支持，详情见如下示例，需在change事件中手动更改value值
https://codesandbox.io/s/vue3-keyboard-n59et

**Comment by liujiujin2006** [comment]
> > > > 不指定v-model时，输入框绑定的数据不会改变，也不会触发onchange，oninput等事件，输入数据input绑定值不会改变，失去作用
> > > > https://codesandbox.io/s/vite-vue3-keyboard-forked-ih3rg?file=/src/App.vue
> > > 
> > > 
> > > 可以再fork看下抛出的钩子调用情况 https://codesandbox.io/s/vite-vue3-keyboard-18oo4?file=/src/App.vue
> > 
> > 
> > 大概明白了，这种模式使用虚拟键盘输入时只是通过js改变了当前聚焦input的值，并不会触发input原生onchange事件，假如有个表单如下:
> > ```
> >   <div class="form-group">
> >     <label>账号</label>
> >     <input data-mode="number" class="form-control" v-model="name" />
> >   </div>
> >   <div class="form-group">
> >     <label>密码</label>
> >     <input data-mode="en" type="password" class="form-control" v-model="psw" />
> >   </div>
> > ```
> > 
> > 
> > 如何才能比较方便的做双向数据绑定呢？
> 
> v1.0.1版本新增了form表单的支持，详情见如下示例，需在change事件中手动更改value值
> https://codesandbox.io/s/vue3-keyboard-n59et

谢谢，完美！
