### ISSUE TITLE
咨询：手写输入咨询

### ISSUE THREAD

**Issue by WeMissing** [cangshudada/vue-keyBoard-next#4]
handApi 请问可选的值有哪些？请问识别引擎是免费开源的吗？

**Comment by cangshudada** [comment]
目前demo中手写识别的接口是根据win10手写识别dll调整成的，有相关需求的可以让后端同学处理下。
目前demo中的手写识别接口不建议直接上生产环境，因为它随时会停用，demo只是提供一个手写识别的演示。

**Comment by cangshudada** [comment]
> handApi 请问可选的值有哪些？请问识别引擎是免费开源的吗？

目前demo中手写识别的接口是根据win10手写识别dll调整成的，有相关需求的可以让后端同学处理下。
目前demo中的手写识别接口不建议直接上生产环境，因为它随时会停用，demo只是提供一个手写识别的演示。

**Comment by WeMissing** [comment]
好的，十分感谢，请问如何与Linux的fcitx对接呢？或者我们加一下好友？QQ:329245767
