### ISSUE TITLE
如果第一次点击, 焦点点在了字中间 , 输入会输在字的最后面.  这个可以解决吗   还是不好解决

### ISSUE THREAD

**Issue by a982246809** [cangshudada/vue-keyBoard-next#5]
![image](https://user-images.githubusercontent.com/56909676/142337250-78c149ce-935e-40a3-b544-5c73f41cc51f.png)

**Comment by cangshudada** [comment]
可以取光标聚焦位置来判断下次文字应该往何处进行差值，大致代码逻辑如下，年底项目过紧，后面我会优化这个bug,你可以先fork优化，处理好也欢迎提pr

> function insertInputTxt(id, insertTxt) {
    var elInput = document.getElementById(id);
    var startPos = elInput.selectionStart;
    var endPos = elInput.selectionEnd;
    if (startPos === undefined || endPos === undefined) return
    var txt = elInput.value;
    var result = txt.substring(0, startPos) + insertTxt + txt.substring(endPos)
    elInput.value = result;
    elInput.focus();
    elInput.selectionStart = startPos + insertTxt.length;
    elInput.selectionEnd = startPos + insertTxt.length;
}

**Comment by cangshudada** [comment]
done
