### ISSUE TITLE
不支持文本域

### ISSUE THREAD

**Issue by chenmingye** [cangshudada/vue-keyBoard-next#7]
可以让文本域也触发键盘吗

**Comment by cangshudada** [comment]
v1.0.2版本已经支持textarea 欢迎安装使用

**Comment by chenmingye** [comment]
ok  感谢

**Comment by chenmingye** [comment]
好像没生效呢😭

**Comment by cangshudada** [comment]
> 好像没生效呢😭

https://codesandbox.io/s/dazzling-gagarin-vwttd8?file=/src/App.vue   看下是否用法正确  1.0.2版本目前是支持到了textarea
