### ISSUE TITLE
手写模式下删除点击删除键不能删除输入框中的文字

### ISSUE THREAD

**Issue by lym1996** [cangshudada/vue-keyBoard-next#9]
手写模式下删除点击删除键不能删除输入框中的文字

**Comment by lym1996** [comment]
![image](https://user-images.githubusercontent.com/39801992/224202684-8abd56f9-1541-4f26-b535-e867877f154c.png)
这里是不是应该修改成这样

**Comment by cangshudada** [comment]
> ![image](https://user-images.githubusercontent.com/39801992/224202684-8abd56f9-1541-4f26-b535-e867877f154c.png) 这里是不是应该修改成这样

感谢指正，1.0.4版本会修复这个问题
